apiVersion: apps/v1
kind: Deployment
metadata:
  name: insuranceportaldeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - name: insuranceclient
        image: kanchanbhong/insuranceclient:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
